---
## Version-specific settings that override the values in cfg/config.yaml
master:
  apiserver:
    confs:
      - /var/snap/k8s/common/args/kube-apiserver
  scheduler:
    confs:
      - /var/snap/k8s/common/args/kube-scheduler
  controllermanager:
    confs:
      - /var/snap/k8s/common/args/kube-controller-manager
    kubeconfig:
      - /etc/kubernetes/controller.conf

node:
  kubelet:
    cafile:
      - "/etc/kubernetes/pki/client-ca.crt"
    svc:
      - "/etc/systemd/system/snap.k8s.kubelet.service"
    confs:
      - "/var/snap/k8s/common/args/kubelet"
    kubeconfig:
      - "/etc/kubernetes/kubelet.conf"
  proxy:
    confs:
      - /var/snap/k8s/common/args/kube-proxy
    kubeconfig:
      - /etc/kubernetes/proxy.conf
    svc:
      - "/etc/systemd/system/snap.k8s.kube-proxy.service"
